// <auto-generated />
using System;
using FashionDressingGame.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionDressingGame.Migrations
{
    [DbContext(typeof(FashionGameDbContext))]
    partial class FashionGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FashionDressingGame.Database.EAppearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Acne")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Dimples")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FaceShape")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Freckles")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HairStyle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkinTone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Appearances");
                });

            modelBuilder.Entity("FashionDressingGame.Database.EBottom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Bottoms");
                });

            modelBuilder.Entity("FashionDressingGame.Database.ECharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("AppearanceID")
                        .HasColumnType("int");

                    b.Property<int>("CharacterGrade")
                        .HasColumnType("int");

                    b.Property<int?>("ClothingID")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppearanceID")
                        .HasDatabaseName("IX_ECharacter_Appearance");

                    b.HasIndex("ClothingID")
                        .HasDatabaseName("IX_ECharacter_Clothing");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("FashionDressingGame.Database.EClothing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Accessory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("BottomId")
                        .HasColumnType("int");

                    b.Property<string>("FormalWear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gloves")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("JewelryId")
                        .HasColumnType("int");

                    b.Property<int?>("OuterWearId")
                        .HasColumnType("int");

                    b.Property<string>("OutfitTheme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Shoe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BottomId")
                        .HasDatabaseName("IX_EClothing_Bottom");

                    b.HasIndex("JewelryId")
                        .HasDatabaseName("IX_EClothing_Jewelry");

                    b.HasIndex("OuterWearId")
                        .HasDatabaseName("IX_EClothing_OuterWear");

                    b.HasIndex("TopId")
                        .HasDatabaseName("IX_EClothing_Top");

                    b.ToTable("Clothings");
                });

            modelBuilder.Entity("FashionDressingGame.Database.EJewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Anklets")
                        .HasColumnType("longtext");

                    b.Property<string>("Chains")
                        .HasColumnType("longtext");

                    b.Property<string>("Cufflinks")
                        .HasColumnType("longtext");

                    b.Property<string>("Earrings")
                        .HasColumnType("longtext");

                    b.Property<string>("Watches")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Jewelries");
                });

            modelBuilder.Entity("FashionDressingGame.Database.EOuterWear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OuterWearName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OuterWearType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OuterWears");
                });

            modelBuilder.Entity("FashionDressingGame.Database.ETop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tops");
                });

            modelBuilder.Entity("FashionDressingGame.Database.ECharacter", b =>
                {
                    b.HasOne("FashionDressingGame.Database.EAppearance", "Appearance")
                        .WithMany()
                        .HasForeignKey("AppearanceID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FashionDressingGame.Database.EClothing", "Clothing")
                        .WithMany()
                        .HasForeignKey("ClothingID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Appearance");

                    b.Navigation("Clothing");
                });

            modelBuilder.Entity("FashionDressingGame.Database.EClothing", b =>
                {
                    b.HasOne("FashionDressingGame.Database.EBottom", "Bottom")
                        .WithMany()
                        .HasForeignKey("BottomId");

                    b.HasOne("FashionDressingGame.Database.EJewelry", "Jewelry")
                        .WithMany()
                        .HasForeignKey("JewelryId");

                    b.HasOne("FashionDressingGame.Database.EOuterWear", "OuterWear")
                        .WithMany()
                        .HasForeignKey("OuterWearId");

                    b.HasOne("FashionDressingGame.Database.ETop", "Top")
                        .WithMany()
                        .HasForeignKey("TopId");

                    b.Navigation("Bottom");

                    b.Navigation("Jewelry");

                    b.Navigation("OuterWear");

                    b.Navigation("Top");
                });
#pragma warning restore 612, 618
        }
    }
}
